name 'mean-dev-vm'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures mean-dev-vm'
long_description 'Installs/Configures mean-dev-vm'
version '0.1.0'
